### ISSUE TITLE
Add migration mechanism

### ISSUE THREAD

**Issue by joneslee85** [lotus/model#115]
**UPDATE**: Please see proposed changes in my PR https://github.com/lotus/model/issues/144

What: Schema Migration for SQL adapter
How:
* Wrap [Sequel::Migrator](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Migrator.html) vs Writing from scratch?
* Migrator class has `up`, `down` method
* Schema file is the source of truths, and it should not reflect local changes of DB schema.
* There is `db/schema.rb` for `/lib` and `apps/<app_name>/db/schema.rb` for app
* Stop users from abusing migration to do data migration (I know - the wording 'migration' is confusing eh?)
* Allow migrations to be stored in 1 level deep or many level deep folder under (as like Rails)
* Follow Sequel Migrator DSL vs Rails DSL
* Generator is to be done in lotusrb gem, and the core classes is to be done in model gem
* The UX for the generator:

  + `lotus generate migration oh_my_god` will generate migration for `/lib`
  + `LOTUS_APP=web lotus generate migration oh_my_lord` will generate migration for `/apps/web`
  OR
  + `lotus generate migration web:oh_my_lord`

**Comment by AlfonsoUceda** [comment]
the migrations should be stored in db/migrations, what do you think?
the name of the file should be add the timestamp for sorting purpose.

what is this? ```Support schema file location configuration```

:+1: other things

**Comment by AlfonsoUceda** [comment]
what about to create rake tasks like rails has, starting with minimum rake tasks like `rake db:create`

```
rake db:create                               # Creates the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:create:all to create all databases in the config)
rake db:drop                                 # Drops the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:drop:all to drop all databases in the config)
rake db:fixtures:load                        # Load fixtures into the current environment's database
rake db:migrate                              # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)
rake db:migrate:status                       # Display status of migrations
rake db:rollback                             # Rolls the schema back to the previous version (specify steps w/ STEP=n)
rake db:schema:cache:clear                   # Clear a db/schema_cache.dump file
rake db:schema:cache:dump                    # Create a db/schema_cache.dump file
rake db:schema:dump                          # Create a db/schema.rb file that is portable against any DB supported by AR
rake db:schema:load                          # Load a schema.rb file into the database
rake db:seed                                 # Load the seed data from db/seeds.rb, db/seeds/*.seeds.rb and db/seeds/ENVIRONMENT/*.seeds.rb
rake db:seed:common                          # Load the seed data from db/seeds.rb and db/seeds/*.seeds.rb
rake db:seed:development                     # Load the seed data from db/seeds.rb, db/seeds/*.seeds.rb and db/seeds/development/*.seeds.rb
rake db:seed:development:company_highlights  # Load the seed data from /home/alfonso/Proyectos/aegon-web/db/seeds/development/company_highlights.seeds.rb
rake db:seed:development:development         # Load the seed data from /home/alfonso/Proyectos/aegon-web/db/seeds/development/development.seeds.rb
rake db:seed:development:pages               # Load the seed data from /home/alfonso/Proyectos/aegon-web/db/seeds/development/pages.seeds.rb
rake db:seed:development:scenarios           # Load the seed data from /home/alfonso/Proyectos/aegon-web/db/seeds/development/scenarios.seeds.rb
rake db:seed:development:testimonies         # Load the seed data from /home/alfonso/Proyectos/aegon-web/db/seeds/development/testimonies.seeds.rb
rake db:seed:original                        # Load the seed data from /home/alfonso/Proyectos/aegon-web/db/seeds.rb
rake db:setup                                # Create the database, load the schema, and initialize with the seed data (use db:reset to also drop the database first)
rake db:structure:dump                       # Dump the database structure to db/structure.sql
rake db:structure:load                       # Recreate the databases from the structure.sql file
rake db:version                              # Retrieves the current schema version number
```

**Comment by joneslee85** [comment]
```
the migrations should be stored in db/migrations, what do you think?
```

+1, I like that. 


Regarding `Support schema file location configuration` - I'd prefer users not doing long data migration (migration that does not change schema structure)

**Comment by alexsun** [comment]
* attributes a minimal, think, anyway should be declared few validations in each entity
* rake tasks for parsing entities, watch changes or send events
* (idea) may possible: use validation rules for generate a proper Sequel.migration source
* additional classic migration can be difficult

new schema at first time, later do alter table, but it is very big deal or not
it look like a good abstraction over storage

**Comment by alexsun** [comment]
> * There is db/schema.rb for /lib and apps/<app_name>/db/schema.rb for app

migration is a fundamental process of controlling the database schema, later it data, but I believe each migrations should be close to the entity not to application, but here has many cases.

**Comment by KillaPL** [comment]
I'd love to have that. Client insisted on rails and I at least negotiated using Lotus::Model, but the lack of migrations sort of killed that idea: (
