### ISSUE TITLE
Add SQL transactions support

### ISSUE THREAD

**Issue by jodosha** [lotus/model#133]
This should be implemented in `Sql::Query`.
Here's the related Sequel documentation: http://sequel.jeremyevans.net/rdoc/files/doc/transactions_rdoc.html

I'd say to not support/document `Sequel::Rollback`. Using exceptions for control flow is always a poor choice. If an exception is raised as side effect, the transaction should be rolled back.

```ruby
transaction do
  raise `Sequel::Rollback` # this will rollback anyway because of Sequel, but it's a poor style that we shouldn't encourage
end
```

```ruby
transaction do
  some_dangerous_method! # if this raises an exception, the transaction should be rolled back
end
```

The second style is the one that we should encourage/document.

/cc @stevehodgkiss @joneslee85

**Comment by AlfonsoUceda** [comment]
something like that using sequel like the link provided:

```ruby
def transaction(options = {})
   DB.transaction(options) do
      yield # if a exception is raised here, then the rollback is fired.
   end
end

**Comment by jodosha** [comment]
@AlfonsoUceda yes, but we don't have a `DB` constant. `SqlAdapter` holds an instance variable called `@connection`, which is the same Sequel type of `DB`.

**Comment by jodosha** [comment]
Because the only high level object that we expose to developers is a repository, we should consider to add that method there. Example `BookRepository.transaction { ... }`.

**Comment by AlfonsoUceda** [comment]
@jodosha can you assing to me please? I'm going to do a PR later or in this weekend

**Comment by AlfonsoUceda** [comment]
@jodosha I have a dude with the implementation, If you use the Repository.transaction I think you will use the repository inside, isn't it? I give you 2 examples but I think it should be explicitly done.

what do you think?

```ruby
UserRepository.transaction { UserRepository.first }
# or
UserRepository.transaction { first }
```

**Comment by jodosha** [comment]
@AlfonsoUceda It should be a public method and context free (first option in your example).

A bit of explanation, this can be useful for complex scenarios where several entities needs to be persisted atomically, and eventually rolled back in case of error.

```ruby
class Signup
  def initialize(params)
    @user = User.new(params[:user])
    @account = Account.new(params[:account])
  end

  def call
    AccountRepository.transaction do
      AccountRepository.create(@account)
      UserRepository.create(@user)
    end
  end
end
```
