### ISSUE TITLE
Add default option to #attribute in collection

### ISSUE THREAD

**Issue by AlfonsoUceda** [lotus/model#136]
Suppose we have this mapper

```ruby
mapper = Lotus::Model::Mapper.new do
   collection :users do
     entity User

     attribute :id,    Integer
     attribute :name,  String
     attribute :admin, Boolean, default: -> { false }
   end
 end

 u = User.new(name: 'Luca', admin: true)
 UserRepository.persist(u)
 u.admin #=> true

 u = User.new(name: 'Luca')
 UserRepository.persist(u)
 u.admin #=> should be false instead nil
```

**Comment by fidothe** [comment]
There's a bigger problem here: imagine that the admin column in the example above is non-NULLable in addition to having a default set. Currently, if you don't explicitly set the value in the entity then Lotus sends `column => nil` on serialisation. This causes Postgres, at least, to choke and error - you can't explicitly set a non-nullable value to null.

It also suggests that we're explicitly setting columns with default values to null when we might expect them to use the column default

**Comment by theCrab** [comment]
```sh
$ LOTUS_ENV=test bundle exec lotus db prepare
Unsupported ruby class used as database type: Boolean (Sequel::Error)
```
How did you define the Sequel's `TrueClass` `FalseClass`?

**Comment by jodosha** [comment]
@theCrab We use Sequel as migration engine. The list of Ruby types is defined here: http://lotusrb.org/guides/migrations/create-table/ :smile_cat:

**Comment by jodosha** [comment]
Closing this for now, as we want to narrow the scope as much as possible before to hit 1.0.
