### ISSUE TITLE
Memory adapter does not support repository query chaining

### ISSUE THREAD

**Issue by fredwu** [lotus/model#153]
Hi,

Due to the different implementation of the sql and memory adapters, the memory one does not support query chaining like [this](https://github.com/lotus/model/blob/4f3aba549cc3c68ba9789500ac868543a800e4df/lib/lotus/model/adapters/sql/query.rb#L567-L617).

In fact, the memoy adapter's [`Query#method_missing`](https://github.com/lotus/model/blob/4f3aba549cc3c68ba9789500ac868543a800e4df/lib/lotus/model/adapters/memory/query.rb#L444-L450) does not even work properly as it was copy-pasted from the sql adapter - in the memory adapter there is no `@context` variable, though as demonstrated below, we could simply get the context (repository) from the collection:

```patch
diff --git a/lib/lotus/model/adapters/memory/query.rb b/lib/lotus/model/adapters/memory/query.rb
index 8c4c4ea..1141ed7 100644
--- a/lib/lotus/model/adapters/memory/query.rb
+++ b/lib/lotus/model/adapters/memory/query.rb
@@ -442,14 +442,20 @@ module Lotus

           protected
           def method_missing(m, *args, &blk)
-            if @context.respond_to?(m)
-              apply @context.public_send(m, *args, &blk)
+            if @collection.repository.respond_to?(m)
+              apply @collection.repository.public_send(m, *args, &blk)
             else
               super
             end
           end

           private
+          def apply(query)
+            dup.tap do |result|
+              result.conditions.push(*query.conditions)
+            end
+          end
+
           # Apply all the conditions and returns a filtered collection.
           #
           # This operation is idempotent, but the records are actually fetched
```

This solves the problem but it's been a few months since I started looking at Lotus again, I'm not sure whether this is a proper fix for it. Please discuss. :)

**Comment by fredwu** [comment]
It also appears for `apply` causes issues here, the chained method would actually alter the collection. Removing the use of `apply` seems to address this issue.

**Comment by jodosha** [comment]
@fredwu Hello. Parity of features between adapters is really hard to achieve. Please consider Memory adapter as a basic tool to get started with some code, without worrying about to setup a real database.

Query chaining is something that I've built with SQL adapter in mind, because Sequel made it really easy to implement.

To be clear, if this feature can be easily ported to the memory adapter, I'd be really happy to merge a PR. I'll leave it to you, if you have time and will to craft one. Thank you very much.

**Comment by fredwu** [comment]
@jodosha Thanks Luca! I'll try look into this. :)
