### ISSUE TITLE
Wrong inherited configuration

### ISSUE THREAD

**Issue by jodosha** [lotus/model#154]
**Reported by: @mwallasch**

In Lotus Container applications we use `Lotus::Model` directly in `lib/bookshelf.rb` to setup connection params and mapping.

Imagine that we have two applications: `web` and `admin`. When we load those apps, because `Lotus::Model` is activated, we duplicate the framework and create `Web::Model` and `Admin::Model`, respectively.

Those duplicated frameworks **inherit the wrong configuration**. At this point `Lotus::Model` becomes a master to copy settings from. If `Lotus::Model.configure` connects to a Postgres database, also `Web::Model` and `Admin::Model` connect to.

This causes unwanted connections against the database.

/cc @lotus/core-team

**Comment by mwallasch** [comment]
:+1:
