### ISSUE TITLE
two locations for mapping

### ISSUE THREAD

**Issue by tomkadwill** [lotus/model#158]
Is it potentially confusing to have two places to define mappings (in a freshly generated application)?

There is one under: `lib/example_app.rb` and one under `apps/web/config/mapping.rb`

**Comment by joneslee85** [comment]
Yes, it kinda is. But the idea is slice app could also have its own adapter. I am open for suggestion that makes thing less confusing, maybe adding more comment to explain that?

**Comment by tomkadwill** [comment]
@joneslee85 Yes I agree, a better comment would help. Can you give me an example of what you mean by 'the idea is slice app could also have its own adapter'?

**Comment by AlfonsoUceda** [comment]
@tomkadwill Imagine you use redis in one of your slices, maybe it makes sense one of the slices has it own adaptaer
