### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by smt116** [lotus/model#168]
Hi there,

https://github.com/lotus/model/blob/master/lib/lotus/model/adapters/sql_adapter.rb#L44-L49

Sequel by default sets `max_connections` to 4. Maybe it should be possible to allow user to set higher value? When you are using Puma as a webserver for your application, you are able to use more than 4 threads and each thread can "talk" with database using its own connection. It can be helpful on jruby and rbx in the future

**Comment by jodosha** [comment]
@smt116 Hey, I think this makes sense. What if we use the URI format and pass extra configuration arguments as params?

```
postgres://localhost/?max_connections=16
```

**Comment by smt116** [comment]
I didn't thought about it. Thanks.

**Comment by KamilLelonek** [comment]
What is the status here? Can we modify this value?

**Comment by jodosha** [comment]
@KamilLelonek yes, you can.

**Comment by KamilLelonek** [comment]
Great! Where and how then? I cannot find any mention of that in [the readme](https://github.com/hanami/model/blob/master/README.md).

**Comment by jodosha** [comment]
@KamilLelonek In the connection URL. Does it work for you?
