### ISSUE TITLE
Map default value for entity

### ISSUE THREAD

**Issue by joneslee85** [lotus/model#189]
If my column DB has a default value, should we pick this up when we define `attributes` for Entity?

Atm, ofcourse I could reader like this:

```
class MyEntity
  def my_value
    @my_value || "my default value"
  end
end
```

However I think we should provide automatic default value mapping. Thoughts?

cc @jodosha @AlfonsoUceda @solnic

**Comment by jodosha** [comment]
Duplicate of #136
