### ISSUE TITLE
Make Repository#execute private

### ISSUE THREAD

**Issue by jodosha** [lotus/model#190]
Ditto.

**Comment by jodosha** [comment]
@peterberkenbosch Can you please take care of it? Thank you very much.

**Comment by mjbellantoni** [comment]
@jodosha is this task as simple as moving this method into the private portion of `Repository`?

**Comment by AlfonsoUceda** [comment]
@mjbellantoni yes

**Comment by mjbellantoni** [comment]
I've taken a shot at this in pull #193.

**Comment by jodosha** [comment]
Implemented by #193
