### ISSUE TITLE
Execute raw query postgres

### ISSUE THREAD

**Issue by darwinrc** [lotus/model#191]
When trying to execute a raw query through postgresql adapter, the returned value from the method is a Fixnum representing the number of matches instead of the rows. When trying to simulate Sequel behavior as shown in link below, passing a block to the method to cursor the results, that block is not interpreted and a Fixnum is still returned.

The execute method in Sequel can be seen here:

https://github.com/jeremyevans/sequel/blob/98659b904ce13c094c90f59d294a4ba33534030b/lib/sequel/adapters/postgres.rb#L163-L173

**Comment by jodosha** [comment]
@darwinrc Sorry for the late reply on this. This is a good idea. Would you love to implement it yourself? We'll be happy to merge as soon as you'll craft it.

**Comment by jodosha** [comment]
@darwinrc Hello again, I forgot to mention that you can do something like this:

```ruby
result_set = ArticleRepository.execute("SELECT * FROM articles")
result_set.each_hash do |result|
  result # -> { id: 123, title: "Introducing transactions", body: "lorem ipsum"}
end

puts result_set.class # => SQLite3::ResultSet
```

See https://github.com/lotus/model/blob/master/lib/lotus/repository.rb#L589-L592

I'm closing this for now, and open a ticket to promote command/query separation for repositories.

**Comment by darwinrc** [comment]
Thanks a lot @jodosha I'll take that into account.
