### ISSUE TITLE
Be able to add extension to Sequel connection

### ISSUE THREAD

**Issue by cecillem** [lotus/model#197]
Hi everyone,

I'm wondering if there is a way I can add the `pg_json` extension to the Sequel connection?

I forked and tried this https://github.com/DealGrocer/model/commit/dc95e0f932ec6dfddb54fd3671bf1f95bc8b47e8 and it seems to be working but I'm not quite sure if that is how it should be done.

Thoughts?

Thanks in advance.

**Comment by jodosha** [comment]
@cecillem Hello and thank you for bringing this idea.

There are a few things to modify:

  * The option should be called `:extensions` instead of `:extension`.
  * We should be able to test it. In the linked code, there is only the [fixture](https://github.com/DealGrocer/model/commit/dc95e0f932ec6dfddb54fd3671bf1f95bc8b47e8#diff-3d9ed706a598dca3884ea15e15197b3eR19), but we don't verify it.

Can you please amend the code and open a PR here? Thank you.

**Comment by cecillem** [comment]
Hi @jodosha appreciate the quick response.

Yeah I agree that it needs it's own test.

I want the test to be something like this,
```
    describe 'given database connection is PostgreSQL' do
      let(:config) { Lotus::Model::Config::Adapter.new(type: :sql, uri: PG_CONNECTION_STRING, extensions: [:pg_json]) }

      it 'instantiates adapter with the extensions option' do
        adapter = config.build(mapper)
        connection = adapter.instance_variable_get('@connection')
        connection.must_respond_to :pg_json
      end
    end
```
to test that the connection responds to an `extension`, in this scenario it will be `pg_json`.

However that would mean that I have to require the `pg` gem and instantiate an actual pg db. I'm hesitant to that because I think it's too much for a small code change...

What do you think?

**Comment by jodosha** [comment]
@cecillem If you look at master, we now have tests that run with PG.

I've read Sequel documentation, extensions can be loaded at three level:

  * Global `Sequel.extension :foo` (which I hope we can avoid to make Lotus::Model a good Ruby citizen)
  * Connection `connection = Sequel.connect('...'); connection.extension :foo`
  * Dataset `conn = Sequel.connect('...'); ds = conn[:users]; ds.extension :foo`.

Your proposed approach targets the second case (connection), but we should be aware of the fact that it's up to the extension developer to provide compatibility with one of the three scenarios.

For instance, you can't do `ds.extension :pg_array`, it's only applicable at the higher levels.

So we should be careful with this.

**Comment by jodosha** [comment]
@cecillem We haven't heard you since two weeks. :smile: Are you still interested to introduce this great feature? Please let us to know :smiley:

**Comment by jodosha** [comment]
Closing this for now, as it isn't high priority.
Keeping track of this idea here: https://trello.com/c/rVuuMCxG
