### ISSUE TITLE
Invalid connection URI results in PG::ConnectionBad: FATAL: database error

### ISSUE THREAD

**Issue by emilford** [lotus/model#199]
There seems to be a bug when running `lotus db create` and other db-related commands on a new application:

`PG::ConnectionBad: FATAL:  database "Eric" does not exist (Sequel::DatabaseConnectionError)`

I haven't had a chance to dig into it fully, but the problem seems to stem from the following method:

```
 def new_connection
  uri = URI.parse(@connection.uri)
  scheme, userinfo, host, port = uri.select(:scheme, :userinfo, :host, :port)

  uri  = "#{ scheme }://"
  uri += "#{ userinfo }@" unless userinfo.nil?
  uri += host
  uri += ":#{ port }" unless port.nil?

  Sequel.connect(uri)
end
```

It looks like the concatenated `uri` string does not include a database name.  PG is attempting to use the default database `Eric` instead of the configured database name.  I was able to temporarily get around this bug by passing `@connection.uri` to `Sequel.connect`.

/cc @nickcoyne

**Comment by nickcoyne** [comment]
I'm no expert on Sequel, but it seems Sequel cannot run `CREATE` against postgresql. If I change `postgres_adapter.rb` to use the  `createdb` shell command, then the database is created as expected.

**Comment by emilford** [comment]
I think :point_up: might be right.  I've come across several posts/comments that mention creating the db via `createdb` as a prerequisite for Sequel.

**Comment by jodosha** [comment]
@emilford Thanks for reporting this. I agree, `createdb` is more reliable. Merged the fix. Thank you all :tada:
