### ISSUE TITLE
id not assigned to the entity on create

### ISSUE THREAD

**Issue by pascalbetz** [lotus/model#206]
According to the documentation in Repository:
```
...
ArticleRepository.create(article) # creates a record
#   article.id # => 23
```
the ID (primary key for RDBMS) should get assigned upon create which is not the case.
Failing Testcase here: https://github.com/pascalbetz/lotus-model/commit/c5e5150f811e84290cd7d03e12e77f88cdc8b5a6

**Comment by jodosha** [comment]
@pascalbetz the returning value of `.create` has the assigned id. This is because we want to apply coercions to the given entity.

```ruby
article = Article.new(comments_count: '100')
article = ArticleRepository.create(article)
article.id # => 1
article.comments_count # => 100
```

This is a matter of outdated documentation. Can you please open another PR to fix it? Thank you.

**Comment by pascalbetz** [comment]
@jodosha so you don't want to modify the entity passed in as argument?

Something like this will fail:
```
user = User.new(...)
UserRepository.create(user)
article = Article.new(user_id: user.id) # failure here: user.id is nil
ArticleRepositry.create(article)
```
but i would actually expect it to work (i only looked up the documentation after i realized my code is not working)

This would lead to something like
```
article = Article.new(...)
article = ArticleRepositry.create(article)
...
```
whenever you need to have the id (i.e. when you associate records). Looks error prone and superfluous to me. Care to explain the idea a bit more?

**Comment by pascalbetz** [comment]
@jodosha 

I fixed the docs. https://github.com/lotus/model/pull/214 so that it is aligned with the code.

Still think that it would be better to assign the id to the entity that is passed in. Less error prone (even lotus model tests are not testing the right thing because of this!) for the user and things might even get trickier when associations are added:

```
article = Article.new
1000.times do
  article.comments << Comment.new
end
created_article = ArticleRepository.create(article)

puts created_article.comments.size #=> ?
puts created_article.comments.first.object_id == article.comments.first.object_id #=> ?
```
Will it clone/copy the associated objects as well?

Still be interested to learn why you think that the passed entity should not have the id assigned. I'll create another issue for this.

**Comment by AlfonsoUceda** [comment]
@pascalbetz IMO I prefer your approach because it's less error prone and you don't have to assing variables but I don't know if this behaviour is planned. what do you say @jodosha ?

does the repository pattern say something abouyt this?

**Comment by pascalbetz** [comment]
@AlfonsoUceda thanks for the feedback: if i understand correctly then L:M actually did assign the id a while ago. This was dropped because coercion is applied on the values (the entity returned from those calls has coerced attributes). So without looking into code i think:


```ruby
p = Person.new(age: "25") # a string
p1 = PersonRepository.persist(p)
p.age #=> "25" (String)
p1.age # => 25 (a number)
```
is the current behaviour .

**Comment by AlfonsoUceda** [comment]
ah you're right @jodosha said that in his previous feedback.

Maybe we have to found some "fix" to do the coercions and modify the id but for now it isn't our priority, @jodosha @joneslee85 what do you think?

**Comment by pascalbetz** [comment]
This PR will fix the doc so it is in sync with the current behaviour. I created an issue (https://github.com/lotus/model/issues/215) for the discussion where i describe some problems i see with the current approach. Would welcome some feedback there.

**Comment by jodosha** [comment]
@pascalbetz I'm closing this for now, because we need a wider discussion on the API improvements.

/cc @lotus/core-team
