### ISSUE TITLE
Add convenient Repository.find_by() and Repository.find_all_by() helpers

### ISSUE THREAD

**Issue by joneslee85** [lotus/model#224]
At the moment, I find that the lacking of `find_by()` and `find_all_by()` which find and return one or many entities makes my work very tedious. I have to repeat myself again many times, having method in Repository to do same job.

Just want to throw it out here for discussion

**Comment by pascalbetz** [comment]
Maybe i misunderstood:

Isn't one of the intention of the repository to provide a clear interface that reveals the intention? Having generic methods would work against that.

**Comment by AlfonsoUceda** [comment]
@joneslee85 for me it doesn't make sense use `find_all_by()` this is a `where`, `find_by()` can be replaced with `where().first`, can you give us an example of your problem?

**Comment by joneslee85** [comment]
@AlfonsoUceda can you? fix me if I am wrong, the rule is *All the queries are private*, thus `where()` or `first()` must be wrapped inside a `query` block and in a public method of the repo, this is what I meant about the repetitiveness

**Comment by joneslee85** [comment]
so here is an example

```
User.find_by(username: 'trung')

#VS

class User
  def self.find_by_username(username)
    query { where(username: username) }.first
  end
end
```

**Comment by pascalbetz** [comment]
_User_  => _UserRepository_ ?

You would want to add a "magic" _find_by_/_find_all_by_ method to the repository? I guess this would reduce the code you have to write (i agree on that one) but violate some of the points mentioned in http://lotusrb.org/guides/models/repositories/ (Private Queries section). Mainly the clear intent would be missing.

**Comment by AlfonsoUceda** [comment]
I agree with @pascalbetz

**Comment by jodosha** [comment]
Agreed on NOT implementing this. :smile:
