### ISSUE TITLE
Rack::URLMap throws Cannot find Lotus::Model adapter FileSystemAdapter

### ISSUE THREAD

**Issue by skinofstars** [lotus/model#227]
I'm trying to mount a Lotus app on a subpath using 

```
require './lotus-app/config/environment'
run Rack::URL(
  '/lotus-app' => Lotus::Container.new
)
```

This throws the following error

/var/lib/gems/2.1.0/gems/lotus-model-0.4.1/lib/lotus/model/config/adapter.rb:99:in `rescue in instantiate_adapter': Cannot find Lotus::Model adapter FileSystemAdapter (Lotus::Model::Config::AdapterNotFound)

**Comment by joneslee85** [comment]
@skinofstars are you using lotus-model in your app?

**Comment by skinofstars** [comment]
I have it in there, but I probably don't need it at the moment. Should that matter?

**Comment by joneslee85** [comment]
@skinofstars it does not matter, but trying to remove it first as it is optional component and see if the error persists

**Comment by skinofstars** [comment]
@joneslee85 right, using Rack::URL works fine when lotus::model is removed.

**Comment by joneslee85** [comment]
@skinofstars will you be able to dig in further?

**Comment by skinofstars** [comment]
@joneslee85 I'm happy to have a look in a couple of days.

**Comment by joneslee85** [comment]
@skinofstars  :+1:

**Comment by joneslee85** [comment]
want any help?

**Comment by skinofstars** [comment]
Ok, just come back, re-added the gem to my project and the problem no longer exists. If I come across it again, I'll re-open.
