### ISSUE TITLE
How to run the sample with Mysql?

### ISSUE THREAD

**Issue by chenge** [lotus/model#234]
![2015-09-02 11 44 16](https://cloud.githubusercontent.com/assets/252333/9622610/cca467e6-5167-11e5-8954-efd80bea32b1.png)

**Comment by joneslee85** [comment]
@chenge have you included `mysql2` gem in your Gemfile?

**Comment by chenge** [comment]
![2015-09-02 6 01 28](https://cloud.githubusercontent.com/assets/252333/9628301/8205333e-519c-11e5-8db0-7f4bfd7064e8.png)

**Comment by joneslee85** [comment]
can you change the URI to `mysql2://`?

**Comment by chenge** [comment]
mysql2:// works， Thank you!
