### ISSUE TITLE
Postgres pattern matching on Query#where

### ISSUE THREAD

**Issue by adlersantos** [lotus/model#243]
Hi Guys,

Is it possible to use Postgres pattern matchers on `Query#where`?

```ruby
class PersonRepository
  include Lotus::Repository

  def self.with_similar_name(name)
    query do
      where("first_name ILIKE '%#{name}%'")
    end
  end
```

Otherwise, then I can probably do it via `SqlAdapter#execute`. How may I sanitize the interpolation of `name` in this manner?

**Comment by AlfonsoUceda** [comment]
@adlersantos hi sorry for the late response, yes you can, you have to use a block ;)
```ruby

  def self.with_similar_name(name)
    query do
      where { "name ILIKE '%#{name}%'" }
    end
  end
```

**Comment by adlersantos** [comment]
Got it, @AlfonsoUceda. Thank you! :)
