### ISSUE TITLE
Display attributes for #to_s

### ISSUE THREAD

**Issue by joneslee85** [lotus/model#246]
Imagine I have following Entity:

```
class Institution
  include Lotus::Entity

  attributes :name, :code
end
```

when I instantiate a new instance:

```
irb> i = Institution.new(name: 'School of Art')
irb> i
=> #<Institution:0x007f82efabb2c8 @name ="School of Art'>
```

we could see that only assigned attributes are displayed. I think it'd be better if we display all attributes of the entity for inspection (even if they are nil):

So the output should be:

```
irb> i
=> #<Institution:0x007f82efabb2c8 @name ="School of Art' @code=nil>
```

Thoughts?

**Comment by jodosha** [comment]
@joneslee85 :+1: Should it be `#inspect` instead of `#to_s`?

**Comment by AlfonsoUceda** [comment]
:+1: because no displaying attributes can be weird
