### ISSUE TITLE
[Proposal] Async methods for repositories 

### ISSUE THREAD

**Issue by lucasallan** [lotus/model#252]
### Async methods 
I'd like to suggest to add `Async` methods to `repository`, something like:

```ruby
future = ArticleRepository.async_where(author_id: 23).order(:published_at).limit(8)
future.get # to fetch the result
```

Basically, these methods will always return a `Future`, something similar to how Cassandra Ruby Driver works: http://datastax.github.io/ruby-driver/features/asynchronous_io/

For the `Future` implementation, we could use concurrent-ruby https://github.com/ruby-concurrency/concurrent-ruby .

#### Reference:
Scala Async DB Drivers: https://github.com/mauricio/postgresql-async

**Comment by jodosha** [comment]
@lucasallan Thanks for the suggestion, but this seems a unneeded complex feature for now. Low priority :mouse:

**Comment by lucasallan** [comment]
@jodosha Fair enough! I know we have limited human resources right now, but I could definitely work on it, unless you have something else that I can work on.
