### ISSUE TITLE
Show error message for `createdb` failure

### ISSUE THREAD

**Issue by cllns** [lotus/model#264]
I'm using [Postgres.app](http://postgresapp.com/) on OS X, and I just ran into a problem running `lotus db create`

```
 ~> lotus db create
/Users/sean/.gem/ruby/2.1.6/gems/lotus-model-0.5.0/lib/lotus/model/migrator/postgres_adapter.rb:29:in ``': No such file or directory - createdb (Errno::ENOENT)
	from /Users/sean/.gem/ruby/2.1.6/gems/lotus-model-0.5.0/lib/lotus/model/migrator/postgres_adapter.rb:29:in `create'
	from /Users/sean/.gem/ruby/2.1.6/gems/lotus-model-0.5.0/lib/lotus/model/migrator.rb:84:in `create'
	from /Users/sean/.gem/ruby/2.1.6/gems/lotusrb-0.5.0/lib/lotus/commands/db/create.rb:9:in `start'
	from /Users/sean/.gem/ruby/2.1.6/gems/lotusrb-0.5.0/lib/lotus/commands/db.rb:31:in `create'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/sean/.gem/ruby/2.1.6/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
```

The problem was that running the `createdb ...` on my computer didn't succeed. I needed to follow [these directions](http://postgresapp.com/documentation/cli-tools.html) (i.e. add `createdb` to my PATH) in order to make it work.

Related: #200, #262

I solved it by looking at `postgres_adapter.rb`, but should we see if `createdb` fails, and show an error saying 'running `createdb` failed` instead of the above?

**Comment by joneslee85** [comment]
@cllns definitely this could be improved by having a check for `createdb` and failed fast if the tool is not available, would you be able to create a PR?

**Comment by cllns** [comment]
I can create a PR :)

If we want to check for `createdb` ahead of time, the best solution looks like using [`find_exectuable`](https://github.com/ruby/ruby/blob/trunk/lib/mkmf.rb#L1572) from 'mkmf' to do so (included in standard library). The downside to that is that it prints `checking for createdb... yes` to stdout. We could use its helper method, [`find_executable0`](https://github.com/ruby/ruby/blob/trunk/lib/mkmf.rb#L1528), but that's marked for internal use only (and, accordingly, has a terrible name) though it is not private. Or we could try to suppress stdout just for that command.

```
 ~> irb -rmkmf
irb(main):001:0> find_executable('ls')
checking for ls... yes
=> "/bin/ls"
irb(main):002:0> find_executable0('ls')
=> "/bin/ls"
```

Another option would be to wrap the `popen3` call in a `begin` block and `rescue SystemCallError`, which seems simplest to me. The biggest downside I see with this approach is that it increases the length and complexity of that method definition, though I might be able to figure out a way to clean it up.

Here are the options I presented, in the order I prefer:

- Rescue `SystemCallError`
- Use `find_executable` and allow it to print to stdout
- Use `find_executable` and suppress stdout
- Use `find_executable0` 

Thoughts @joneslee85?

**Comment by joneslee85** [comment]
@cllns TIL `find_executable`, I am totally fine with the message. To me it is much simpler than `popen3`. Give it a shot

**Comment by cllns** [comment]
Ah sorry, I should've linked to the code. Popen3 is already being used, I only propose adding begin/rescue around it: https://github.com/lotus/model/blob/master/lib/lotus/model/migrator/postgres_adapter.rb#L106

Still want to go with `find_executable`, or do you think rescuing SystemCallError would be better?

**Comment by joneslee85** [comment]
@cllns does `find_executable` work under JRuby? If not, we go `popen3`
