### ISSUE TITLE
No output on `lotus db migrate`

### ISSUE THREAD

**Issue by davidpelaez** [lotus/model#267]
After running the command I see no output. For instance in my machine I see an error of my bundle, but no confirmation of the migration occurring. 

```
WARN: Unresolved specs during Gem::Specification.reset:
      mail (~> 2.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

After checking on the DB the migration did occur but I couldn't tell so this is a usability issue, specially considering that DB migrations make people somewhat nervous!

**Comment by jodosha** [comment]
@davidpelaez We designed it by following the UNIX philosophy: [Rule of Silence](http://www.linfo.org/rule_of_silence.html)

> [...] when a program has nothing surprising, interesting or useful to say, it should say nothing.

It's the same of this:

```shell
➜ touch foo
➜ rm foo # success, no output
➜ rm foo
rm: foo: No such file or directory
➜
```

**Comment by davidpelaez** [comment]
OK. I get where it comes from. I think putting the user's emotion first would be better. The machine using the program is less common that the user using it directly so I would prefer to prioritize on that direction. Sometimes you want a silent program so a flag like in curl makes sense `curl -s`. Also another option is using stderr by default for information messages. I understand the philosophical perspective but I feel it comes at the expense of user centered design so I wanted to share my opinion in case you'd want to reconsider. Thank you for your work on Lotus, it's a refreshment to work in a such a different architecture. :)
