### ISSUE TITLE
Make .update consistent with .initialize

### ISSUE THREAD

**Issue by TheSmartnik** [lotus/model#275]
When we initiailize, we [check](https://github.com/lotus/model/blob/master/lib/lotus/entity.rb#L191-L196) if attribute can be assigned. What if we make the same for [.update](https://github.com/lotus/model/blob/master/lib/lotus/entity.rb#L282-L286)?

**Comment by jodosha** [comment]
@TheSmartnik Hi, why this feature request? Update expects an entity as input. So the control is provided by entity and update can indirectly take advantage of it.

**Comment by TheSmartnik** [comment]
@jodosha Hi, sorry not sure we are on the same page. I meant [entity update method](https://github.com/lotus/model/blob/master/lib/lotus/entity.rb#L191-L196), which accepts hash

**Comment by jodosha** [comment]
@TheSmartnik The goal is to remove soon mutable state for entities. So it's very likely that `Entity#update` will be deprecated/removed in a few months.

**Comment by TheSmartnik** [comment]
@jodosha Oh, I see. Thanks :smile:
