### ISSUE TITLE
Handle adapter exceptions as Lotus errors

### ISSUE THREAD

**Issue by Moratorius** [lotus/model#276]
When creating an entity, the `SqlAdapter` does not raise a `Lotus::Model::Error`.  Exceptions are bubbled up from the adapter, e.g. `Sequel::UniqueConstraintViolation` is exposed directly to the application.  Applications should only be concerned with the Lotus interface and not the underlying adapter implementation.

Ideally there would be an equivalent `Lotus::Model::Error` for each of the `Sequel::DatabaseError` subclasses (https://github.com/jeremyevans/sequel/blob/4.30.0/lib/sequel/exceptions.rb) so the application doesn't have to inspect the error message to identify specific error classes.

**Comment by joneslee85** [comment]
@Moratorius that's true, would you be able to instantiate a PR for this? TIA

**Comment by Moratorius** [comment]
Yes.

**Comment by Moratorius** [comment]
I've opened a PR to address this issue here: https://github.com/lotus/model/pull/281

**Comment by jodosha** [comment]
Resolved by #281
